Mvc/Controllers/CommentsController.cs
using Business.Abstract;
using Core.Entities;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly UserManager<AppUser> _userManager;

        public CommentsController(ICommentService commentService, UserManager<AppUser> userManager)
        {
            _commentService = commentService;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> _ListComments(int Id)
        {
            ViewBag.Id = Id;
            var comments = await  _commentService.GetCommentsWithUserByPostId(Id);
            foreach (var comment in comments)
            {
                TimeSpan date = DateTime.Now.Subtract(comment.CreatedDate);

                if (date.TotalSeconds < 60)
                {
                    ViewData[comment.Id.ToString()] = $"{date.Seconds.ToString()} sn önce";
                }
                else if (date.TotalMinutes < 60)
                {
                    ViewData[comment.Id.ToString()] = $"{date.Minutes.ToString()} dk önce";
                }
                else if (date.TotalHours < 24)
                {
                    ViewData[comment.Id.ToString()] = $"{date.Hours.ToString()} sa önce";
                }
                else
                {
                    ViewData[comment.Id.ToString()] = $"{date.Days.ToString()} gün önce";
                }
            }
            return PartialView(comments);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int Id, Comment comment)
        {
			var userId = _userManager.Users.Where(x => x.UserName == User.Identity.Name).SingleOrDefault().Id;
            comment.AppUserId = userId;
            comment.CreatedDate = DateTime.Now;
            comment.PostId = Id;
            comment.Id = 0; // parametreden gelen postId değerini commentId'ye atadığı için sıfırladım
            
            await _commentService.CreateComment(comment);
            return RedirectToAction("Index", "Posts");
        }

        public async Task<IActionResult> Delete(Comment comment)
        {
            await _commentService.DeleteComment(comment);
            return RedirectToAction("Index", "Posts");
        }
    }
}

Mvc/Controllers/ProfileController.cs
using Core.Entities;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mvc.Models.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc.Controllers
{
    [AllowAnonymous]
    [Route("[controller]")]
    public class ProfileController : Controller
    {
		private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext _context;

        public ProfileController(UserManager<AppUser> user, AppDbContext context)
        {
            _userManager = user;
            _context = context;
        }

        [Route("{userName}")]
        public async Task<IActionResult> Index(string userName)
        {
            AppUser user = _userManager.Users
                .Where(x => x.UserName == userName)
                .Include(x => x.Posts)
                .Include(x => x.Favorites)
                .Include(x => x.Comments)
                .Include(x => x.Followeds)
                .Include(x => x.Followings)
                .AsSplitQuery() // for more performance
                .SingleOrDefault();

            var posts = _context.Posts
                .Where(x => x.AppUser == user)
                .Include(x => x.Comments)
                .Include(x => x.Favorites) 
                .AsSplitQuery()
                .OrderByDescending(x => x.CreatedDate)
                .ToList();

            UserPosts userPosts = new()
            {
                AppUser = user,
                Posts = posts
            };

            var follows = _context.Follows.Include(x => x.Following).Include(x => x.Followed).ToList();

            if(User.Identity.IsAuthenticated)
            {
                int authUserId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;

                if (user != null)
                {
                    var follow = _context.Follows.FirstOrDefault(x => x.FollowingId == authUserId && x.FollowedId == user.Id);

                    if (follows.Contains(follow))
                    {
                        ViewData["followLink"] = "Takibi Bırak";
                    }
                    else
                    {
                        ViewData["followLink"] = "Takip Et";
                    }
                }
            }
            else
            {
                ViewData["followLink"] = "Takip Et";
            }
            
            return View(userPosts);
        }

        [Route("_ListUsers")]
        public async Task<IActionResult> _ListUsersAsync()
        {
            var users = _userManager.Users.ToList();

            if(User.Identity.IsAuthenticated)
            {
                users.Remove(await _userManager.FindByNameAsync(User.Identity.Name));
            }
            
            return PartialView(users);
        }
    }
}

Mvc/Views/Comments/_ListComments.cshtml
@model IEnumerable<Comment>

    <!--CreateComment-->
<div class="card mb-4 sticky-top">
    <div class="card-header bg-transparent">
        <form class="form-inline" asp-controller="Comments" asp-action="Create" asp-route-id="@ViewBag.Id" method="post">
            <div class="input-group w-100">
                <input type="text" maxlength="500" name="Content" placeholder="Yorum yap..." class="form-control form-control-md">
                <button class="btn btn-info" type="submit">Yorumla</button>
            </div>
        </form>
    </div>
</div>
<hr />

<!--ListComments-->

<div id="plist" class="mt-2 people-list">
    <ul class="list-unstyled chat-list mt-2 mb-0">
        @foreach (var comment in Model)
        {
            <a asp-action="Index" asp-controller="Profile" asp-route-userName="@comment.AppUser.UserName">
            <li class="clearfix">
                <img src=@comment.AppUser.ProfilePicture alt="avatar">
                <div class="about">
                    <div class="name">@comment.AppUser.FirstName @comment.AppUser.LastName</div>
                    <div class="status"> <i class="fa fa-circle online"></i> @comment.AppUser.UserName </div>
                    <p class="media-text text-danger">@comment.Content</p>
                    
                </div>
                <small class="float-right">@ViewData[comment.Id.ToString()]</small>
            </li>
            </a>
            @if (comment.AppUser.UserName == User.Identity.Name)
            {
                <a asp-controller="Comments" asp-action="Delete" asp-route-id="@comment.Id" class="btn btn-danger btn-sm rounded-circle mt-auto"><i class="bi-trash"></i></a>
            }
            <hr />
        }
    </ul>
</div>