Mvc/Controllers/FollowController.cs
using Business.Abstract;
using Core.Entities;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc.Controllers
{
    public class FollowController : Controller
    {
        private readonly IFollowService _followService;
        private readonly AppDbContext _context;
        public FollowController(AppDbContext context, IFollowService followService)
        {
            _context = context;
            _followService = followService;
        }
        public async Task<IActionResult> FollowUnFollow(int Id, bool? isComingFromProfile)
        {
            var userName = User.Identity.Name;
            AppUser user = _context.Users.Where(x => x.UserName == userName).FirstOrDefault();
            AppUser followedUser = _context.Users.Where(x => x.Id == Id).FirstOrDefault();

            var follows = _context.Follows.Include(x => x.Following).Include(x => x.Followed).ToList();

            var follow = _context.Follows.FirstOrDefault(x => x.FollowingId == user.Id && x.FollowedId == Id);

            if (followedUser != null)
            {
                if (follows.Contains(follow))
                {
                    await _followService.UnFollow(follow);
                }
                else
                {
                    Follow newFollow = new()
                    {
                        FollowingId = user.Id,
                        FollowedId = Id
                    };

                    await _followService.Follow(newFollow);
                }
            }   

            if(isComingFromProfile == true)
            {
                return RedirectToAction("index", "profile", new {followedUser.UserName});
            }
            else
            {
                return RedirectToAction("index", "posts");
            }
            
        }


        [AllowAnonymous]
        public IActionResult _ListFollowings(int Id)
        {
            var followings = _context.Follows.Include(x => x.Following).Include(x => x.Followed).Where(x => x.Following.Id == Id).ToList();

            return PartialView(followings);
        }


        [AllowAnonymous]
        public IActionResult _ListFollowers(int Id)
        {
            var followeds = _context.Follows.Include(x => x.Following).Include(x => x.Followed).Where(x => x.Followed.Id == Id).ToList();

            return PartialView(followeds);
        }
    }
}

Mvc/Controllers/PostsController.cs
using Business.Abstract;
using Core.Entities;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService _postService;
        private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext _context;
        public PostsController(IPostService postService, UserManager<AppUser> userManager, AppDbContext context)
        {
            _postService = postService;
            _userManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index(int page = 1, int pageSize = 10)
        {
            //var posts = await _postService.GetAllWithUserAndComments();
            var posts = _postService.GetAllWithUserAndCommentsForPagedList().ToPagedList(page, pageSize);
            string authUserName = User.Identity.Name;
            int authUserId = (await _userManager.FindByNameAsync(authUserName)).Id;
         
            AppUser user = _context.Users.Include(x => x.Followeds).Where(x => x.Id == authUserId).FirstOrDefault();
            var follows = _context.Follows.Include(x => x.Following).Include(x => x.Followed).ToList();

            #region For follow suggestions 
            // Code review needed for this section

            var users = _userManager.Users.ToList();
            Random randomnbr = new();
            var x = users.Count;

            int authUserIndex = users.IndexOf(user);

            List<int> values = new List<int>();

            int nbr1 = randomnbr.Next(x);

            int nbr2 = randomnbr.Next(x);

            while (nbr1 == authUserIndex)
            {
                nbr1 = randomnbr.Next(x);
            }
            values.Add(nbr1);

            while (nbr1 == nbr2 || nbr2 == authUserIndex)
            {
                nbr2 = randomnbr.Next(x);
            }
            values.Add(nbr2);

            int nbr3 = randomnbr.Next(x);

            while (nbr3 == nbr2 || nbr3 == nbr1 || nbr3 == authUserIndex)
            {
                nbr3 = randomnbr.Next(x);
            }
            values.Add(nbr3);


            ViewBag.randomUser1 = $"{users[nbr1].FirstName} {users[nbr1].LastName}";
            ViewBag.randomUser2 = $"{users[nbr2].FirstName} {users[nbr2].LastName}";
            ViewBag.randomUser3 = $"{users[nbr3].FirstName} {users[nbr3].LastName}";

            ViewBag.userName1 = users[nbr1].UserName;
            ViewBag.userName2 = users[nbr2].UserName;
            ViewBag.userName3 = users[nbr3].UserName;

            ViewBag.userId1 = users[nbr1].Id;
            ViewBag.userId2 = users[nbr2].Id;
            ViewBag.userId3 = users[nbr3].Id;

            ViewBag.usrPp1 = users[nbr1].ProfilePicture;
            ViewBag.usrPp2 = users[nbr2].ProfilePicture;
            ViewBag.usrPp3 = users[nbr3].ProfilePicture;

            #endregion
            var usersForFollowSuggestions = _userManager.Users.Where(x => x.UserName != User.Identity.Name).ToList();

            foreach (var post in posts)
            {
                var follow = _context.Follows.FirstOrDefault(x => x.FollowingId == user.Id && x.FollowedId == post.AppUserId);

                // Unique bir ViewData key'i için böyle bir yol denendi.
                if (follows.Contains(follow))
                {
                    ViewData[post.Id.ToString()+ "x"] = "Takibi Bırak";
                }
                else
                {
                    ViewData[post.Id.ToString() + "x"] = "Takip Et";
                }

                #region TimeSpan for post created time
                TimeSpan date = DateTime.Now.Subtract(post.CreatedDate);

                if (date.TotalSeconds < 60)
                {
                    ViewData[post.Id.ToString()] = $"{date.Seconds.ToString()} sn önce";
                }
                else if (date.TotalMinutes < 60)
                {
                    ViewData[post.Id.ToString()] = $"{date.Minutes.ToString()} dk önce";
                }
                else if (date.TotalHours < 24)
                {
                    ViewData[post.Id.ToString()] = $"{date.Hours.ToString()} sa önce";
                }
                else
                {
                    ViewData[post.Id.ToString()] = $"{date.Days.ToString()} gün önce";
                }
                #endregion
            }

            return View(posts);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(Post post)
        {
            if(post.Content != null)
            {
                post.CreatedDate = DateTime.Now;
                var userName = User.Identity.Name;
                post.AppUserId = _userManager.Users.Where(x => x.UserName == userName).SingleOrDefault().Id;
                post.OriginalPostOwner = userName;
                await _postService.CreatePost(post);
                return RedirectToAction("Index");
            }
            return NoContent();
        }

        public async Task<IActionResult> Delete(Post post)
        {
            await _postService.DeletePost(post);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RePostAsync(int id, bool? isComingFromProfile)
        {
            Post rePost = new();
            rePost.AppUserId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;
            var userId = rePost.AppUserId;
            
            AppUser user = await _userManager.FindByIdAsync(userId.ToString());
            var post = await _postService.GetPostById(id);
            rePost.OriginalPostOwner = post.AppUser.UserName;
            rePost.Content = post.Content;
            rePost.AppUser = user;
            rePost.CreatedDate = DateTime.Now;
            rePost.IsRepost = true;

            await _postService.CreatePost(rePost);

            if (isComingFromProfile == true)
            {
                return RedirectToAction("index", "profile", new { post.AppUser.UserName });
            }
            else
            {
                return RedirectToAction("index", "posts");
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> PostPage(int Id)
        {
            Post post = await _postService.GetPostById(Id);
            if (post == null) 
            {
                ViewBag.message = "Böyle bir paylaşım yok!";
            }
            return View(post);
        }
    }
}

Mvc/Controllers/ProfileController.cs
using Core.Entities;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mvc.Models.ViewModels;
using System.Linq;
using System.Threading.Tasks;

namespace Mvc.Controllers
{
    [AllowAnonymous]
    [Route("[controller]")]
    public class ProfileController : Controller
    {
		private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext _context;

        public ProfileController(UserManager<AppUser> user, AppDbContext context)
        {
            _userManager = user;
            _context = context;
        }

        [Route("{userName}")]
        public async Task<IActionResult> Index(string userName)
        {
            AppUser user = _userManager.Users
                .Where(x => x.UserName == userName)
                .Include(x => x.Posts)
                .Include(x => x.Favorites)
                .Include(x => x.Comments)
                .Include(x => x.Followeds)
                .Include(x => x.Followings)
                .AsSplitQuery() // for more performance
                .SingleOrDefault();

            var posts = _context.Posts
                .Where(x => x.AppUser == user)
                .Include(x => x.Comments)
                .Include(x => x.Favorites) 
                .AsSplitQuery()
                .OrderByDescending(x => x.CreatedDate)
                .ToList();

            UserPosts userPosts = new()
            {
                AppUser = user,
                Posts = posts
            };

            var follows = _context.Follows.Include(x => x.Following).Include(x => x.Followed).ToList();

            if(User.Identity.IsAuthenticated)
            {
                int authUserId = (await _userManager.FindByNameAsync(User.Identity.Name)).Id;

                if (user != null)
                {
                    var follow = _context.Follows.FirstOrDefault(x => x.FollowingId == authUserId && x.FollowedId == user.Id);

                    if (follows.Contains(follow))
                    {
                        ViewData["followLink"] = "Takibi Bırak";
                    }
                    else
                    {
                        ViewData["followLink"] = "Takip Et";
                    }
                }
            }
            else
            {
                ViewData["followLink"] = "Takip Et";
            }
            
            return View(userPosts);
        }

        [Route("_ListUsers")]
        public async Task<IActionResult> _ListUsersAsync()
        {
            var users = _userManager.Users.ToList();

            if(User.Identity.IsAuthenticated)
            {
                users.Remove(await _userManager.FindByNameAsync(User.Identity.Name));
            }
            
            return PartialView(users);
        }
    }
}

Mvc/Views/Posts/Index.cshtml
@*@model IEnumerable<Post>*@
@model PagedList.Core.IPagedList<Post>
@addTagHelper *,PagedList.Core.Mvc

@await Html.PartialAsync("_CommentModal")

<div class="row">
    
    @await Component.InvokeAsync("LeftColumn")

    <div class="col-md-6  ">
        <div class="middle-column">

            <!------CreatePost------>  
            <div class="card mb-4 ">
                <div class="card-header bg-transparent">
                    <form class="form-inline" asp-controller="Posts" asp-action="CreatePost" method="post">
                        <div class="input-group w-100">
                            <input type="text" maxlength="500" name="Content" id="message" placeholder="Paylaş..." class="form-control form-control-md">
                            <button class="btn btn-info" type="submit">Paylaş</button>
                        </div>
                    </form>
                </div>
            </div>

            <!------ListPosts------>
            @foreach(var post in Model)
            {
                <div class="card custombg">                        
                    <div class="card-body">
                        <div class="media">                             
                            <img src=@post.AppUser.ProfilePicture alt="img" width="55" height="55" class="rounded-circle mr-3">
                            <div class="media-body">
                                <div>
                                    <a asp-controller="Profile" asp-action="@post.AppUser.UserName" class="link">@post.AppUser.FirstName @post.AppUser.LastName</a>

                                    @if (post.IsRepost)
                                    {
                                        <div class="mb-2 text-danger"> @($"Bu paylaşım '{post.OriginalPostOwner}' kişisinden alıntılanmıştır")  </div>
                                    }
                                    
                                    <h6 class="small">@($"@{post.AppUser.UserName}")</h6>
                                </div>                                   
                                <hr>
                                <p class="text-justify">
                                    @post.Content
                                </p>
                            </div>

                            @if(post.AppUser.UserName != User.Identity.Name)
                            {
                                <a asp-controller="Follow" asp-action="FollowUnFollow" asp-route-Id="@post.AppUser.Id" class="btn btn-sm btn-info mr-4">@ViewData[post.Id.ToString()+ "x"]</a>
                            }
                            
                            <small>@ViewData[post.Id.ToString()]</small>
                        </div>

                        <div @*buttons*@ >

                            <div class="btn-group text-sm-center float-right" role="group" aria-label="Basic example" style="margin-top:20px">

                                <a asp-action="Favorite" asp-controller="Favorite" asp-route-id="@post.Id" style="margin-right:20px" type="button" class="btn btn-info rounded-circle btn-sm">
                                    <i class="bi-heart" style="color:black">
                                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">@post.Favorites.Count</span>
                                    </i>
                                </a>

                                <a data-target="/Comments/_ListComments/@post.Id" data-toggle="modal" style="margin-right:20px" type="button" class="commentview btn btn-info btn-sm rounded-circle">
                                    <i class="bi-chat" style="color:black">
                                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">@post.Comments.Count</span>
                                    </i>
                                </a>

                                @if (post.AppUser.UserName != User.Identity.Name && post.IsRepost == false)
                                {
                                    <a asp-action="RePost" asp-controller="Posts" asp-route-id="@post.Id" style="margin-right:20px; color:black" class="btn btn-info btn-sm rounded-circle"><i class="bi-arrow-repeat"></i></a>
                                }

                                <a id="linkforcopy" onclick="copy(@post.Id)" style="margin-right:20px; color:black" class="btn btn-info btn-sm rounded-circle"><i class="bi-send"></i></a>
                              
                            </div>

                            @if(post.AppUser.UserName == User.Identity.Name)
                            {
                                <a asp-controller="Posts" asp-action="Delete" asp-route-id="@post.Id" class="btn btn-danger btn-sm rounded-circle float-left " style="margin-top:20px"><i class="bi-trash"></i></a>
                            }
                        </div>
                    </div>                
                </div>
            }
            <pager list="@Model" asp-action="index" asp-controller="posts"></pager>
        </div>
    </div>

    @await Component.InvokeAsync("RightColumn")
   
</div>

<script>
    function copy(id) {
        var link = `${window.location.host}/Posts/PostPage/${id}`
        navigator.clipboard.writeText(link);
        alert("Link koplayalandı!");
    }
</script>

Mvc/Views/Posts/PostPage.cshtml
@model Post

@await Html.PartialAsync("_CommentModal")

@if (ViewBag.message != null)
{
    <div class="card card-body text-danger ">@ViewBag.message</div>
}
else
{
    <div class="row">
        <div class="col-md-6 offset-3">
            <div class="card custombg">
                <div class="card-body">
                    <div class="media">
                        <img src=@Model.AppUser.ProfilePicture alt="img" width="55" height="55" class="rounded-circle mr-3">
                        <div class="media-body">
                            <div>
                                <a asp-controller="Profile" asp-action="@Model.AppUser.UserName" class="link">@Model.AppUser.FirstName @Model.AppUser.LastName</a>

                                @if (@Model.IsRepost)
                                {
                                    <div class="mb-2 text-danger"> @($"Bu paylaşım '{Model.OriginalPostOwner}' kişisinden alıntılanmıştır")  </div>
                                }

                                <h6 class="small">@($"@{Model.AppUser.UserName}")</h6>
                            </div>
                            <hr>
                            <p class="text-justify">
                                @Model.Content
                            </p>
                        </div>

                        <small>@Model.CreatedDate</small>
                    </div>

                    <div @*buttons*@>

                        <div class="btn-group text-sm-center float-right" role="group" aria-label="Basic example" style="margin-top:20px">

                            <a asp-action="Favorite" asp-controller="Favorite" asp-route-id="@Model.Id" style="margin-right:20px" type="button" class="btn btn-info rounded-circle btn-sm">
                                <i class="bi-heart" style="color:black">
                                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">@Model.Favorites.Count</span>
                                </i>
                            </a>

                            <a data-target="/Comments/_ListComments/@Model.Id" data-toggle="modal" style="margin-right:20px" type="button" class="commentview btn btn-info btn-sm rounded-circle">
                                <i class="bi-chat" style="color:black">
                                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">@Model.Comments.Count</span>
                                </i>
                            </a>

                            @if (Model.AppUser.UserName != User.Identity.Name && Model.IsRepost == false)
                            {
                                <a asp-action="RePost" asp-controller="Posts" asp-route-id="@Model.Id" style="margin-right:20px; color:black" class="btn btn-info btn-sm rounded-circle"><i class="bi-arrow-repeat"></i></a>
                            }

                            <a id="linkforcopy" onclick="copy(@Model.Id)" style="margin-right:20px; color:black" class="btn btn-info btn-sm rounded-circle"><i class="bi-send"></i></a>
                        </div>

                        @if (Model.AppUser.UserName == User.Identity.Name)
                        {
                            <a asp-controller="Posts" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger btn-sm rounded-circle float-left " style="margin-top:20px"><i class="bi-trash"></i></a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    function copy(id) {
        var link = `${window.location.host}/Posts/PostPage/${id}`
        navigator.clipboard.writeText(link);
        alert("Link koplayalandı!");
    }
</script>    